[package]
name = "titania-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "titania"
path = "main.rs"

[dependencies]
argh = "0.1.19"
crossterm = "0.29.0"
dirs = "7.0.0"
titania-model = { version = "0.1.0", path = "../model" }
titania-runtime = { version = "0.1.0", path = "../runtime" }
ureq = "3.4.1"
unicode-width = "0.2.2"
